### ISSUE TITLE
VMware: Debian 8.2 +  Fusion 8.1.0 + HGFS

### ISSUE THREAD

**Issue by rmoriz** [chef/bento#547]
Using `opscode-debian-8.2` bento box with test-kitchen and VMWare Fusion 8.1.0. Tried to get `vagrant-cachier`working, however:

````
-----> Starting Kitchen (v1.5.0)
-----> Creating <rails-debian-82>...
       Bringing machine 'default' up with 'vmware_fusion' provider...
       ==> default: Cloning VMware VM: 'opscode-debian-8.2'. This can take some time...
       ==> default: Verifying vmnet devices are healthy...
       ==> default: Preparing network adapters...
       ==> default: Starting the VMware VM...
       ==> default: Waiting for machine to boot. This may take a few minutes...
           default: SSH address: 172.16.202.187:22
           default: SSH username: vagrant
           default: SSH auth method: private key
           default: 
           default: Vagrant insecure key detected. Vagrant will automatically replace
           default: this with a newly generated keypair for better security.
           default: 
           default: Inserting generated public key within guest...
           default: Removing insecure key from the guest if it's present...
           default: Key inserted! Disconnecting and reconnecting using new SSH key...
       ==> default: Machine booted and ready!
       ==> default: Forwarding ports...
           default: -- 22 => 2222
       ==> default: Setting hostname...
       ==> default: Configuring network adapters within the VM...
       ==> default: Waiting for HGFS kernel module to load...
       The HGFS kernel module was not found on the running virtual machine.
       This must be installed for shared folders to work properly. Please
       install the VMware tools within the guest and try again. Note that
       the VMware tools installation will succeed even if HGFS fails
       to properly install. Carefully read the output of the VMware tools
       installation to verify the HGFS kernel modules were installed properly.
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #create action: [Expected process to exit with [0], but received '1
```

**Comment by rmoriz** [comment]
turns out the official bento vmware images are probably using old VMware tools version or were build on an old VMware Fusion release because of a NAT bug with 8.1.0 (https://blogs.vmware.com/teamfusion/2016/01/workaround-of-nat-port-forwarding-issue-in-fusion-8-1.html).

I could circumvent the issue by manually creating a box on a system with Fusion 8.1.0 installed:

```shell
cd /tmp
git clone https://github.com/chef/bento
cd packer
packer build -only=vmware-iso debian-8.2-amd64.json
vagrant box remove opscode-debian-8.2
vagrant box add opscode-debian-8.2 /tmp/bento/builds/debian-8.2.vmware.box 
```

works with `vagrant-cachier`:

```
       ==> default: Configuring network adapters within the VM...
       ==> default: Waiting for HGFS kernel module to load...
       ==> default: Enabling and configuring shared folders...
           default: -- /Users/rmoriz/.vagrant.d/cache/opscode-debian-8.2: /tmp/vagrant-cache
       ==> default: Configuring cache buckets...
```

related:
- https://blogs.vmware.com/teamfusion/2016/01/workaround-of-nat-port-forwarding-issue-in-fusion-8-1.html
- https://github.com/chef/bento/issues/522

**Comment by cheeseplus** [comment]
In the process of cutting a new release - we kind of expected Vmware to update and were holding out for that but then they axed the Fusion/Workstation teams. I wasn't planning on rebuilding 8.2 as I'll be pushing 8.3 but we probably can do so.

**Comment by josegonzalez** [comment]
@cheeseplus I think you pushed out `2.2.3` recently, though it seems that it didn't fix the HGFS issue (at least not for me). Any ideas?

**Comment by cheeseplus** [comment]
@josegonzalez I pushed a 2.2.4 recently even though the PR for the readme changes hasn't been merged. There is a 2.2.5 that I am working on currently but the vmtools are problematic for all new reasons that I've not yet determined.

**Comment by cheeseplus** [comment]
We've released an updated debian-8.3 image as part of 2.2.5

**Comment by davidmnoriega** [comment]
I'm using vmware fusion 7.1.3 and recently upgraded the ubuntu 14.04 box from 2.2.3 to 2.2.5 and got the no HGFS kernel module error. Downgrading back to 2.2.3, I can see that the kernel module exists at `/lib/modules/3.19.0-25-generic/misc/vmhgfs.ko` but it does not exist in 2.2.5

**Comment by rmoriz** [comment]
Fusion 7 was released 1.5 years ago and it looks like things have changed with Fusion 8.

**Comment by ayanich** [comment]
fwiw, I still get the HGFS errors with the latest 2.2.5 image + vmware 8.1 + ubuntu 14.04.  I dont think the 2.2.5 image was built with vmware-tools version 8.1

**Comment by rmoriz** [comment]
works for me: https://gist.github.com/rmoriz/93ccb81b602f28573779af5fa9b8b323

**Comment by ayanich** [comment]
you are trying with debian 8.3 which is working, and I am on ubuntu 14.04 which is not.

**Comment by cheeseplus** [comment]
Hey folks - let's do a solid for maintainer sanity and keep reports specific to a platform and hypervisor in their own issues. <3

**Comment by rmoriz** [comment]
Okay, can confirm Ubuntu 14.04 has still the HGFS issues with VMware Fusion 8.1 - probably it was not rebuild (only that debian 8.3 mentioned by @cheeseplus)

**Comment by cheeseplus** [comment]
Ubuntu 14.04 was in fact rebuilt but due to HWE kernel issues the vmware tools appear to freak out and fail in some terrifying new way. It's under investigation and folks are welcome to open a specific issue if they want to get it before I do.

**Comment by rmoriz** [comment]
I'm fine with Debian 8.3 + HGFS so I would tend to close this issue.

 Let's open a new issue for Ubuntu + HGFS/HWE, okay?

**Comment by cheeseplus** [comment]
Opened https://github.com/chef/bento/issues/555 and closing this one.

**Comment by davidmnoriega** [comment]
I looked at the change log for vmware tools 10.x, and it only says its supported with vmware fusion 8+, so I'll look at updating.
